services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
    container_name: sort-email-frontend
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - sortemail

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sort-email-backend
    expose:
      - "8000"
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env.production
    restart: unless-stopped
    networks:
      - sortemail

networks:
  sortemail:
    driver: bridge