services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: sort-email-frontend-dev
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    command: ["npm", "run", "dev", "--", "--host"]
    restart: unless-stopped
    depends_on:
      - backend
      
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: sort-email-backend-dev
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      # opcional — crie um .env com sua chave
    env_file:
      - .env.development
    volumes:
      - ./backend:/app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    restart: unless-stopped

volumes:
  frontend_node_modules:
